{{- if .Values.secrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata: { name: app-secret }
spec:
  refreshInterval: 1h
  secretStoreRef: { name: {{ .Values.secrets.storeName | quote }}, kind: SecretStore }
  target: { name: app-secret, creationPolicy: Owner }
  data:
    - secretKey: GREETING
      remoteRef: { key: {{ .Values.secrets.greetingKey | quote }} }
{{- else if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata: { name: app-secret }
type: Opaque
stringData:
  GREETING: "{{ .Values.secret.GREETING }}"
{{- end }}