{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: { name: demo-app }
spec:
  scaleTargetRef: { apiVersion: apps/v1, kind: Deployment, name: demo-app }
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource: { name: cpu, target: { type: Utilization, averageUtilization: {{ .Values.hpa.cpu }} } }
  - type: Resource
    resource: { name: memory, target: { type: Utilization, averageUtilization: {{ .Values.hpa.memory }} } }
{{- end }}