image: { repository: demo-app, tag: "0.1.0" }

replicas: 5

resources:
  requests: { cpu: "300m", memory: "384Mi" }
  limits:   { cpu: "800m", memory: "768Mi" }

env: { READINESS_DELAY_SEC: "10", FAIL_RATE: "0.005" }

# Ensure pod can start: create an in-cluster Secret (until ESO is wired)
secret: { enabled: true, GREETING: "Hello from prod" }
secrets: { enabled: false }

hpa: { enabled: true, minReplicas: 5, maxReplicas: 20, cpu: 65, memory: 70 }

# Keep ingress off unless you installed NGINX+cert-manager locally
ingress: { enabled: false }

# IMPORTANT: render Deployment, not Rollout
rollout: { enabled: false }